#!/bin/sh

################################################################################
# Functions
################################################################################
usage()
{
cat << Help
usage: `basename $0` [OPTION]... [DIRECTORY]

Install OMBU optimized Drupal site in [DIRECTORY]

Options:

  -d [NAME]    Database name. If site is set to install and this option isn't given,
               then you will be prompted to enter this during the install process.
  -u [USER]    Database user. If site is set to install and this option isn't given,
               then you will be prompted to enter this during the install process.
  -p           Prompt for database password.
  -s [SITE]    Site name. If not set, then will default to "Site Name"
  -e [EMAIL]   Site email. If not set, then will default to "example@ombuweb.com"
  -t [THEME]   The type of theme to use for this site. Can either be "starter" or
               "starter_grid".  If not set, then will default to "starter"
  -m [NAME]    The short name for the project (used current for theme name).  If
               not set, then the database name will be used. Shouldn't contain
               spaces or special characters.

Misc:
  -x           Install dev modules and data.
  -n           No install; don't install Drupal site after downloading it
  -h           This help

Help
}

################################################################################
# Command line args
################################################################################

while getopts ":d:u:s:e:pxnh" opt
do
    case $opt in
    d)
      DBNAME=$OPTARG
      ;;
    u)
      DBUSER=$OPTARG
      ;;
    p)
      echo "Enter database password for user $DBUSER:"
      stty -echo; read -r DBPASS; stty echo  # won't display what user types
      ;;
    s)
      SITENAME=$OPTARG
      ;;
    e)
      SITEMAIL=$OPTARG
      ;;
    t)
      THEME=$OPTARG
      ;;
    m)
      SHORTNAME==$OPTARG
      ;;
    n)
      NOINSTALL=true
      ;;
    x)
      DEV=true
      ;;
    h)
      usage
      exit
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      exit
      ;;
    esac
done
shift $(($OPTIND - 1))

# Set defaults
if [ ! $SITEMAIL ]; then
  SITEMAIL='example@ombuweb.com'
fi

if [ ! $SITENAME ]; then
  SITENAME='Site Name'
fi

if [ ! $THEME ]; then
  THEME='starter'
fi

if [ ! $SHORTNAME ]; then
  SHORTNAME=$DBNAME
fi

if [ $* ]; then
  INSTALLDIR=$*

  # Create install directory if it doesn't exist
  echo "+ Creating install directory $INSTALLDIR"
  if [ ! -d $INSTALLDIR ]; then
    mkdir $INSTALLDIR
  fi
else
  usage
  exit
fi

# Get current working directory.
CWD=`pwd`

# define temp directory
# Warning: this directory will be removed at the end of the script, so make sure
# it's a subdirectory
TMP="/tmp/drupalbuild"
if [ ! -d $TMP ]; then
  mkdir $TMP
fi


################################################################################
# Drupal site build
################################################################################
echo "+ Building Drupal code"

# Download make file (can't run it off of github behind private repo)
if [ ! -d $TMP/drupal-installer ]; then
  git clone git@github.com:ombu/drupal-installer.git $TMP/drupal-installer
fi

# Check if build directory exists
if [ -d $INSTALLDIR/public ]; then
  echo "Aborting: $INSTALL/public already exists, delete first before running this script"
  exit 2
fi

# Build drupal site with make file, keeping repo directories
drush make --no-gitinfofile $TMP/drupal-installer/include/ombu7.make "$INSTALLDIR/public"

# Copy ombudashboard example blocks file to default site
cp $INSTALLDIR/public/sites/all/modules/custom/ombudashboard/ombudashboard.admin_blocks.inc.example $INSTALLDIR/public/sites/default/ombudashboard.admin_blocks.inc

echo "+ Drupal build complete"

# Copy default included files
cp $TMP/drupal-installer/include/fabfile.py $INSTALLDIR/
cp $TMP/drupal-installer/include/README.md $INSTALLDIR/

# Copy environment specific settings files.
cp $TMP/drupal-installer/include/settings.* $INSTALLDIR/public/sites/default/

sed -i "" -e "s/__DBNAME__/$DBNAME/g" \
    -e "s/__DBUSER__/$DBUSER/g" \
    -e "s/__DBPASS__/$DBPASS/g" \
    -e "s/__SITENAME__/$SITENAME/g" \
    -e "s/__SITEMAIL__/$SITEMAIL/g" \
    $INSTALLDIR/fabfile.py $INSTALLDIR/README.md $INSTALLDIR/public/sites/default/settings.development.php

cp $INSTALLDIR/public/sites/default/settings.development.php $INSTALLDIR/public/sites/default/settings.php

# Create new repo and first commit
echo "+ Initializing git repo"
cd $INSTALLDIR
git init

# .gitignore file
ignore_file="sites/default/settings.php
sites/default/settings.php
sites/default/files
"

echo $ignore_file > .gitignore

# Add git submodules
echo "+ Setting up submodules"
git submodule add -b drupal7 git@github.com:ombu/drupal-ombucleanup.git public/sites/all/modules/custom/ombucleanup
git submodule add -b drupal7 git@github.com:ombu/drupal-ombudashboard.git public/sites/all/modules/custom/ombudashboard
git submodule add -b drupal7 git@github.com:ombu/drupal-ombuseo.git public/sites/all/modules/custom/ombuseo
git submodule add git@github.com:ombu/drupal-ombuwire.git public/sites/all/modules/custom/ombuwire
git submodule add -b dev git@github.com:ombu/drupal-ombubase.git public/sites/all/themes/ombubase

# Setup theme
echo "+ Setting up theme"
cp -r public/sites/all/themes/ombubase/$THEME public/sites/all/themes/$SHORTNAME
mv public/sites/all/themes/$SHORTNAME/$THEME.info public/sites/all/themes/$SHORTNAME/$SHORTNAME.info
sed -i "" -e "s/name =.*/name = $SITENAME Theme/" \
  -e "s/description =.*/description = $SITENAME Theme/" \
  -e "s/base theme =.*/base theme = $THEME/" \
  public/sites/all/themes/$SHORTNAME/$SHORTNAME.info

if [ -f public/sites/all/themes/$SHORTNAME/template.php ]; then
  sed -i "" -e "s/$THEME/$SHORTNAME/g" public/sites/all/themes/$SHORTNAME/template.php
fi

sed -i "" -e "s/bartik/$SHORTNAME/" public/profiles/ombuprofile/ombuprofile.profile

chmod 0774 public/sites/default
chmod 0664 public/sites/default/settings.php

git add public fabfile.py README.md .gitignore
git commit -m "Initial install of OMBU Base"

if [ $NOINSTALL ]; then
  echo "Called with noinstall option. Exiting before running installer."
  cd $CWD
  exit 0
fi

# Run fabric installer
if [ $DEV ]; then
  fab drupal.build
else
  fab drupal.build:dev=yes
fi

# Change back to original directory
cd $CWD

################################################################################
# Cleanup
################################################################################
# rm -rf $TMP

echo "+ Drupal build complete"
